### ISSUE TITLE
How is one supposed to set this up?

### ISSUE THREAD

**Issue by Shaddox** [flathub/com.eduke32.EDuke32#36]
Good evening,

I am very confused at the moment for how I'm supposed to set this up, for I've tried many things, yet trying to play the game always results in `DUKE3D.GRP not found!` .

I have put `duke3d.grp` and `DUKE.RTS` in so many places and none of them seem to be pleasing. I have put it in `~/Documents/Eduke32` and in `com.eduke32.Eduke32/.config/eduke32`  and in `com.eduke32.Eduke32/.config/eduke32/autoload` and in no place it seems to be detected.

Any assistance would be appreciated since online searches seem to be fruitless.

**Comment by FakeShemp** [comment]
https://github.com/flathub/com.eduke32.EDuke32/issues/6#issuecomment-1133745956

**Comment by ColinKinloch** [comment]
The issue started with https://voidpoint.io/terminx/eduke32/-/commit/ae9b0d412455e36f22139494daa3e8ca8dbea520

**Comment by ColinKinloch** [comment]
EDuke32 is now using `XDG_CONFIG_HOME` in place of home which breaks Steam search.
`XDG_DOCUMENTS_DIR` doesn't seem to exist within my env which means it won't search `~/Documents/EDuke32`.

**Comment by GldRush98** [comment]
I ran in to this bug in the latest update that was from the Discover store (previous version worked).
I installed the test version in the linked patch via shell and that did indeed fix the issue on SteamDeck.

**Comment by ColinKinloch** [comment]
Excellent! Thanks for testing!
It's now [merged upstream](https://voidpoint.io/terminx/eduke32/-/merge_requests/256) so it's just a matter of waiting for the generation of the next tarball and we can remove of the patch.

**Comment by Shaddox** [comment]
After having updated the flatpak today, I can confirm it's all in working order now with `~/Documents/Eduke32 `.
Even more so, I no longer have to second guess myself since the launcher screen now even confirms what directories it's actually scanning for addons.

Thank you very much for your prompt fix!

**Comment by journuit** [comment]
Hi all, first of all thanks for the great work.
For those looking for a place to put their assets with the latest flatpak, what worked for me today was to put them in `~/.var/app/com.eduke32.EDuke32/.config/eduke32/`.
Other places wouldn't work, with the GUI not even launching, I had to find and check the log file to know that the assets weren't found where I orginially put them (tried all the places mentioned above).

**Comment by GldRush98** [comment]
I just updated and the latest flatpak is working fine. It is looking in the Documents folder as it should and is working like it has since this was fixed last summer.

> Using directory /home/deck/
Using directory /home/deck/.config/eduke32/
Started at 2024-03-06 09:09:40.993
EDuke32 r10560-f5cb424be
Built Mar  6 2024 04:28:21, GCC 13.2.0, 64-bit
Using directory /home/deck/Documents/EDuke32/
CPU: AMD Custom APU 0405
Initializing SDL 2.28.5 (SDL-2.28.5-no-vcs)
Using 'x11' video driver.
Detecting video modes for display 0 (ANX7530 U 3")...
Searching for game data...

**Comment by journuit** [comment]
I see that you used a capital D in `~/Documents/EDuke32/`
I tried `~/Documents/Eduke32/` as it is how it was spelled in Shaddok's post above.
I didn't find the relevant information on the website, where the installation instructions only mention windows and MacOS. Maybe an update would be helpful for linux users?

**Comment by journuit** [comment]
`~/Documents/EDUke32` still does not exist on my fedora, even though I successfully launched the app.
I'll have a look at the "join our community" section, thanks.
